version: '3.8'

services:
  postgres:
    image: postgres:13  
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: game
    ports:
      - "5432:5432"      
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - mynetwork

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
